# Generated by Django 3.2.10 on 2021-12-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='babysitter',
            field=models.BooleanField(default=False),
        ),
    ]
