# Generated by Django 3.2.10 on 2021-12-10 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_usermodel_babysitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitterReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('usermodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='DoggyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('breed', models.CharField(max_length=200)),
                ('nature', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='pics')),
                ('usermodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.usermodel')),
            ],
        ),
    ]
